version: 2
jobs:
  build:
    docker:
     - image: circleci/openjdk:10.0.2-jdk-browsers
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - setup_remote_docker:
        version: 18.05.0-ce
        docker_layer_caching: true
    - add_ssh_keys:
        fingerprints:
          - "5f:9d:14:91:16:7c:39:92:67:55:6d:78:65:7e:f4:64"
    - run:
        name: Clone Chassis and services for stubs
        command: |
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/chassis.git ~/chassisRepo
#          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/webservice-mail.git ~/mailRepo
#          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@bitbucket.org:konradboniecki/webservice-account.git ~/accountRepo
    - checkout
#_______________________________________________________________

    - run:
        name: Install maven
        command: |
          sudo apt-get update
          sudo apt-get install maven
    - run:
        name: Install Chassis and stubs for contracts
        command: |
          cd ~/chassisRepo
          mvn clean install -DskipTests=true
#          cd ~/mailRepo
#          mvn clean install -DskipTests=true
#          cd ~/accountRepo
#          mvn clean install -DskipTests=true
    - run:
        name: Download dependencies
        command: |
          mvn dependency:go-offline
    - run:
        name: Build and run tests
        command: |
          mvn clean install

    - store_test_results:
        paths:
        - target/surefire-reports
    - store_artifacts:
        path: target/surefire-reports/surefire-report.html
    - store_artifacts:
        path: target/site/jacoco/
    - store_artifacts:
        path: target/surefire-reports

    - run:
        name: Build and push docker image
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            TAG=$CIRCLE_PROJECT_REPONAME-0.5.$CIRCLE_BUILD_NUM
          fi
          if [ "$CIRCLE_BRANCH" != "master" ]; then
            TAG=$CIRCLE_PROJECT_REPONAME-0.5.$CIRCLE_BUILD_NUM-PR
          fi
          docker build -t konradboniecki/budget:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push konradboniecki/budget:$TAG